# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483deedf532b714af972dab4e6769a5560f1d30671ea68da87b9d0b9833daa4b92ec1087bd9a44c5bbcd7470ad4359d71d4f02fad2c88f83235d9026e4f0fec3

test:
  secret_key_base: c514b46f4843884b4db4d4dd5e6bc9be40911a85d913d4d75d0c78949aa94a89f4289383c44a2399b19c90c9740161b3c12430e1a9c44bc6000ec9c40ea71bfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
